    
resources:
  - name: kubexray_any_branch
    type: GitRepo
    configuration:
      gitProvider: jfrogsolutionsci_github
      path: jfrog/kubexray
      files:
        exclude: .pipelines/.*.yml$
      branches:
        exclude: master

pipelines:
  - name: kubexrayAnyBranch
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kubexray
          dockerImageTag: $run_number
          inputResources:
            - name: kubexray_any_branch
          integrations:
            - name: cpe_pipeline_slack
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting kubexrayAnyBranch branch ${res_kubexray_any_branch_branchName} ${step_name}_buildNumber=${run_number}" 
          onSuccess:
            - send_notification cpe_pipeline_slack --text "kubexrayAnyBranch branch ${res_kubexray_any_branch_branchName} ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "kubexrayAnyBranch branch ${res_kubexray_any_branch_branchName} ${step_name}_buildNumber=${run_number} - FAILED"
