resources:
  - name: kubexray_release
    type: GitRepo
    configuration:
      gitProvider: jfrogsolutionsci_github
      path: jfrog/kubexray
      files:
        exclude: .pipelines/.*.yml$
      branches:
        include: master
      tags:
        include: .*.*.*
      buildOn:
        commit: false
        tagCreate: true

pipelines:
  - name: kubexrayRelease
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kubexray
          dockerImageTag: $res_kubexray_release_gitTagName
          inputResources:
            - name: kubexray_release
          integrations:
            - name: cpe_pipeline_slack
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting kubexrayRelease v$res_kubexray_release_gitTagName ${step_name}_buildNumber=${run_number}" 
          onSuccess:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease v$res_kubexray_release_gitTagName ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease v$res_kubexray_release_gitTagName ${step_name}_buildNumber=${run_number} - FAILED"
      - name: push_image
        type: Bash
        configuration:
          affinityGroup: bldGroup
          environmentVariables:
            TAG_NAME: $res_kubexray_release_gitTagName
            BINTRAY_REPO: ${int_jfrogsolutionsci_bintray_repo//_/-}.bintray.io
          inputResources:
            - name: kubexray_release
              trigger: false
          integrations:
            - name: jfrogsolutionsci_bintray
            - name: cpe_pipeline_slack
          inputSteps:
            - name: build_image
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting kubexrayRelease of docker image ${step_name}_buildNumber=${run_number}" 
          onExecute:
            - docker login -u=${int_jfrogsolutionsci_bintray_user} -p=${int_jfrogsolutionsci_bintray_password} ${BINTRAY_REPO}
            - docker tag kubexray:${TAG_NAME} ${BINTRAY_REPO}/kubexray:${TAG_NAME}
            - docker push ${BINTRAY_REPO}/kubexray:${TAG_NAME}
          onSuccess:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease of docker image v${TAG_NAME} ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease of docker image v${TAG_NAME} ${step_name}_buildNumber=${run_number} - FAILED"
      - name: goreleaser
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.12.5"
          environmentVariables:
            TAG_NAME: $res_kubexray_release_gitTagName
            GITHUB_TOKEN: ${int_jfrogsolutionsci_github_token}
          inputResources:
            - name: kubexray_release
              trigger: false
          integrations:
            - name: jfrogsolutionsci_github
            - name: cpe_pipeline_slack
          inputSteps:
            - name: build_image
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting kubexrayRelease goreleaser v${TAG_NAME} ${step_name}_buildNumber=${run_number}" 
          onExecute:
            - cd $res_kubexray_release_resourcePath
            - ls
            - pwd
            - curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | VERSION=v0.115.0 bash
            - echo "goreleaser finished!!!"
          onSuccess:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease goreleaser v${TAG_NAME} ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "kubexrayRelease goreleaser v${TAG_NAME} ${step_name}_buildNumber=${run_number} - FAILED"
